// Code generated by "stringer -type=Category"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Picture-0]
	_ = x[Mover-1]
	_ = x[Scene-2]
	_ = x[Person-3]
	_ = x[Ball-4]
}

const _Category_name = "PictureMoverScenePersonBall"

var _Category_index = [...]uint8{0, 7, 12, 17, 23, 27}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
