// Code generated by "stringer -type=Category"; DO NOT EDIT.

package categories

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Texture-0]
	_ = x[Circle-1]
	_ = x[Cells-2]
	_ = x[Mover-3]
	_ = x[Game-4]
	_ = x[CellsMover-5]
	_ = x[Player-6]
	_ = x[COUNT-7]
}

const _Category_name = "TextureCircleCellsMoverGameCellsMoverPlayerCOUNT"

var _Category_index = [...]uint8{0, 7, 13, 18, 23, 27, 37, 43, 48}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
