// Code generated by "stringer -linecomment -type=Scheme"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[File-1]
}

const _Scheme_name = "nonefile"

var _Scheme_index = [...]uint8{0, 4, 8}

func (i Scheme) String() string {
	if i < 0 || i >= Scheme(len(_Scheme_index)-1) {
		return "Scheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scheme_name[_Scheme_index[i]:_Scheme_index[i+1]]
}
