// Code generated by "stringer -type=TextItem"; DO NOT EDIT.

package text

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MajorUsage-0]
	_ = x[MinorUsage-1]
	_ = x[KeyUsage-2]
	_ = x[InstallUsage-3]
	_ = x[QuickUsage-4]
	_ = x[LastTextItem-5]
}

const _TextItem_name = "MajorUsageMinorUsageKeyUsageInstallUsageQuickUsageLastTextItem"

var _TextItem_index = [...]uint8{0, 10, 20, 28, 40, 50, 62}

func (i TextItem) String() string {
	if i < 0 || i >= TextItem(len(_TextItem_index)-1) {
		return "TextItem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextItem_name[_TextItem_index[i]:_TextItem_index[i+1]]
}
