// Code generated by "gostringer -type=TextItem"; DO NOT EDIT.

package text

import "fmt"

const _TextItem_name_gostringer = "MajorUsageMinorUsageKeyUsageInstallUsageQuickUsageLastTextItem"

var _TextItem_index_gostringer = [...]uint8{0, 10, 20, 28, 40, 50, 62}

func (i TextItem) GoString() string {
	if i < 0 || i >= TextItem(len(_TextItem_index_gostringer)-1) {
		return fmt.Sprintf("text.TextItem(%d)", i)
	}
	return "text." + _TextItem_name_gostringer[_TextItem_index_gostringer[i]:_TextItem_index_gostringer[i+1]]
}
