// Code generated by "stringer -type=Class"; DO NOT EDIT.

package class

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClassBegin-0]
	_ = x[Game-1]
	_ = x[Ellipse-2]
	_ = x[Texture-3]
	_ = x[Tracker-4]
	_ = x[LifeMover-5]
	_ = x[LifeGrid-6]
	_ = x[Player-7]
	_ = x[CellsOrg-8]
	_ = x[Pane-9]
	_ = x[Vocabulary-10]
	_ = x[ClassEnd-11]
}

const _Class_name = "ClassBeginGameEllipseTextureTrackerLifeMoverLifeGridPlayerCellsOrgPaneVocabularyClassEnd"

var _Class_index = [...]uint8{0, 10, 14, 21, 28, 35, 44, 52, 58, 66, 70, 80, 88}

func (i Class) String() string {
	if i < 0 || i >= Class(len(_Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
