// Code generated by "stringer -type=Genre"; DO NOT EDIT.

package class

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenreBegin-0]
	_ = x[Shape-1]
	_ = x[NumberGrid-2]
	_ = x[GridMover-3]
	_ = x[GenreEnd-4]
}

const _Genre_name = "GenreBeginShapeNumberGridGridMoverGenreEnd"

var _Genre_index = [...]uint8{0, 10, 15, 25, 34, 42}

func (i Genre) String() string {
	if i < 0 || i >= Genre(len(_Genre_index)-1) {
		return "Genre(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Genre_name[_Genre_index[i]:_Genre_index[i+1]]
}
